repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.8
    hooks:
      - id: uv-export
        name: main dependencies
        args: [--no-hashes, --no-dev, --output-file, requirements.txt]
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8
    hooks:
      - id: ruff-check
        args: ["--select", "I", "--fix"]
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
